dist: trusty
sudo: required
language: c
compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update

install:
    # Build dependencies
    - sudo apt-get build-dep -y pidgin

    # Colormake
    - sudo wget https://github.com/renatosilva/colormake/raw/master/colormake.sh -O /usr/local/bin/colormake
    - sudo chmod +x /usr/local/bin/colormake

before_script:
    - cd source

script:
    - ./configure && colormake

notifications:
    email: false
