environment:
    MSYSTEM: MINGW64

build_script:
    # Update
    - C:\msys64\usr\bin\bash --login -c "repman add renatosilva http://packages.renatosilva.net"
    - C:\msys64\usr\bin\bash --login -c "pacman --noconfirm --sync pacboy"
    - C:\msys64\usr\bin\bash --login -c "pacboy --noconfirm update" # Core
    - C:\msys64\usr\bin\bash --login -c "pacboy --noconfirm update" # Rest

    # Build
    - C:\msys64\usr\bin\bash --login -c "pacman --noconfirm --sync easyoptions"
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build/winbuild.sh . --prepare"
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build/winbuild.sh ."
