environment:
    MSYSTEM: MINGW64

build_script:
    # Update
    - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --sysupgrade --sysupgrade # Core
    - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --sysupgrade --sysupgrade # Rest

    # Build
    - C:\msys64\usr\bin\bash --login -c "pacman --noconfirm --sync easyoptions"
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build/winbuild.sh . --prepare"
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build/winbuild.sh ."
