environment:
    MSYSTEM: MINGW64

cache:
    - C:\msys64\var\cache\pacman\pkg

build_script:
    # Oddities
    - C:\msys64\usr\bin\bash --login -c "rm -rf '/c/Program Files/Git'"
    - C:\msys64\usr\bin\bash --login -c "pacman --noconfirm --sync pacman-mirrors"
    - C:\msys64\usr\bin\bash --login -c "pacman --noconfirm --sync openssh"

    # Build
    - C:\msys64\usr\bin\bash --login -c "wget http://packages.renatosilva.me/easyoptions-git-r36.7304200-1-any.pkg.tar.xz"
    - C:\msys64\usr\bin\bash --login -c "pacman --noconfirm --upgrade easyoptions-git-r36.7304200-1-any.pkg.tar.xz"
    - C:\msys64\usr\bin\bash --login -c "$(cygpath -ua ${APPVEYOR_BUILD_FOLDER})/build/winbuild.sh . --prepare"
    - C:\msys64\usr\bin\bash --login -c "$(cygpath -ua ${APPVEYOR_BUILD_FOLDER})/build/winbuild.sh . --offline"
